### ISSUE TITLE
No module named 'GoSyncModel'

### ISSUE THREAD

**Issue by zkispal** [hschauhan/gosync#42]
Followed the installation instructions on unmodified release of Ubuntu 20.04. When I want to run GoSync getting the following error message: 

********@Linux:~/Downloads$ GoSync
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/GoSync/GoSyncController.py", line 36, in <module>
    from .GoSyncSettingsPage import SettingsPage
ModuleNotFoundError: No module named 'GoSync.GoSyncSettingsPage'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/GoSync/GoSync.py", line 24, in <module>
    from .GoSyncController import GoSyncController
  File "/usr/local/lib/python3.8/dist-packages/GoSync/GoSyncController.py", line 38, in <module>
    from GoSyncModel import GoSyncModel, ClientSecretsNotFound
ModuleNotFoundError: No module named 'GoSyncModel'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/GoSync", line 5, in <module>
    from GoSync.GoSync import main
  File "/usr/local/lib/python3.8/dist-packages/GoSync/GoSync.py", line 27, in <module>
    import GoSyncModel
ModuleNotFoundError: No module named 'GoSyncModel'

**Comment by arentoine** [comment]
Hello,

this was very little typo.  It's now fixed.  Can you go through section 3 of the wiki (https://github.com/arentoine/gosync/wiki) and confirm it's resolved.

Thanks for reporting the bug !

**Comment by zkispal** [comment]
Thanks for the fix. Updated from git and now it works.
