### ISSUE TITLE
Failed Start @ Ubuntu 22.04 LTS Python3

### ISSUE THREAD

**Issue by Pommes16** [hschauhan/gosync#64]
After successful installation and authentification, i met a problem at start up by running
```
$  GoSync
```
Error message:
```
Traceback (most recent call last):
  File "/usr/local/bin/GoSync", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/GoSync/GoSync.py", line 38, in main
    controller = GoSyncController()
  File "/usr/local/lib/python3.10/dist-packages/GoSync/GoSyncController.py", line 171, in __init__
    selectionPage = SelectionPage(nb, self.sync_model)
  File "/usr/local/lib/python3.10/dist-packages/GoSync/GoSyncSelectionPage.py", line 37, in __init__
    headerFont = wx.Font(11.5, wx.SWISS, wx.NORMAL, wx.NORMAL)
TypeError: Font(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: argument 1 has unexpected type 'float'
  overload 3: argument 1 has unexpected type 'float'
  overload 4: argument 1 has unexpected type 'float'
  overload 5: argument 1 has unexpected type 'float'
  overload 6: argument 1 has unexpected type 'float'
  overload 7: argument 1 has unexpected type 'float'
```
Any one knows how to fix this?

**Comment by ferraroluc** [comment]
I have the same problem. It could be a dependencies version problem.

In my case, I am using Manjaro Linux. And I tried both the PIP and the AUR version. Both with the same problem.

**Comment by ferraroluc** [comment]
So, to make it work, I changed line 37 of the file `GoSyncSelectionPage.py` to:

```py
headerFont = wx.Font(11, wx.SWISS, wx.NORMAL, wx.NORMAL)
```

Also, since some options were not visible, I adjusted the size from line 111 of the file `GoSyncController.py` to:

```py
wx.Frame.__init__(self, None, title="GoSync", size=(490,700), style=mainWindowStyle)
```

**Comment by hschauhan** [comment]
Thanks @ferraroluc. That is the right fix. I will fix this in repository.
