### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by Opfour** [hschauhan/gosync#66]
Just tried installing this app and got the following error:

```
root@merovingiantwo:~# pip install GoSync
Collecting GoSync
  Downloading GoSync-0.53-py2.py3-none-any.whl (176 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 176.1/176.1 kB 2.0 MB/s eta 0:00:00
Collecting google-auth-httplib2
  Downloading google_auth_httplib2-0.1.0-py2.py3-none-any.whl (9.3 kB)
Collecting wxpython>=4.1.0
  Downloading wxPython-4.2.0.tar.gz (71.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.0/71.0 MB 4.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-0l7y2ll3/wxpython_0e8aebab3f0d4341bf31391248888ac2/setup.py", line 27, in <module>
          from buildtools.config import Config, msg, opj, runcmd, canGetSOName, getSOName
        File "/tmp/pip-install-0l7y2ll3/wxpython_0e8aebab3f0d4341bf31391248888ac2/buildtools/config.py", line 30, in <module>
          from attrdict import AttrDict
      ModuleNotFoundError: No module named 'attrdict'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
Thoughts?

**Comment by Opfour** [comment]
Also tried Installing with normal user; same result

**Comment by ComedyTomedy** [comment]
Yeah you need to install wxpython, check the install instructions linked in the README. If you're onan apt-based system, try:

    sudo apt-get install python3-wxgtk4.0

I've had other issues since, and couldn't get GoSync to work, but I think that was what solved this one.

**Comment by hschauhan** [comment]
Thanks @ComedyTomedy for the correct response. @Opfour did it solve the problem for you?
@ComedyTomedy what is the problem you are facing?

**Comment by ComedyTomedy** [comment]
Too many to remember I'm afraid! My lack of Python knowledge probably didn't help. In the end, I found that `google-drive-ocamlfuse` was good enough for my use case (which was figuring out what to delete to free up gmail space, I don't actually use GDrive), and I'm afraid I don't have time at the moment to help debug.
